### ISSUE TITLE
[HW] Gurmehar Bakshi

### ISSUE THREAD

**Issue by gsbakshi** [datastaxdevs/appdev-week1-todolist#118]
**Name:** Gurmehar Singh Bakshi
**Email:** greaser.bakshi@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/gsbakshi/

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-07-11 at 11 53 13 PM](https://user-images.githubusercontent.com/61559056/125206940-53e71100-e2a7-11eb-9c89-cb35be26340d.png)

![Screenshot 2021-07-12 at 12 00 50 AM](https://user-images.githubusercontent.com/61559056/125206949-58abc500-e2a7-11eb-9992-834bba6b2ec7.png)

![Screenshot 2021-07-12 at 12 00 59 AM](https://user-images.githubusercontent.com/61559056/125206951-59dcf200-e2a7-11eb-8b44-bc77daad62fd.png)

![Screenshot 2021-07-12 at 12 01 25 AM](https://user-images.githubusercontent.com/61559056/125206952-5b0e1f00-e2a7-11eb-94ed-9fd62eee074c.png)

![Screenshot 2021-07-12 at 12 02 00 AM](https://user-images.githubusercontent.com/61559056/125206954-5ba6b580-e2a7-11eb-853f-5d2227362d5a.png)

![Screenshot 2021-07-12 at 12 13 21 AM](https://user-images.githubusercontent.com/61559056/125206955-5c3f4c00-e2a7-11eb-82dc-e0ea9f5133e8.png)

![Screenshot 2021-07-12 at 12 21 00 AM](https://user-images.githubusercontent.com/61559056/125206957-5cd7e280-e2a7-11eb-8239-5f14bc4b63c0.png)

I have also attached my github repo link below. If you could give any feedback (especially components splitting, or code organization) that would be much appreciated.
https://github.com/gsbakshi/todos-w-astra

This homework was quite interesting. Had a lot of fun doing this and learning. Looking forward to doing the tik tok and netflix clone exercises as well.

**Comment by SonicDMG** [comment]
Hi there Gurmehar, thank you for your submission. The todo app looks good, but I am missing the from scratch react app from step 2 of the homework.
2. Create a React app from scratch using NPX. Follow [these instructions](https://github.com/datastaxdevs/react-basics). Take a screenshot of your final working app.

Please complete that step and provide a screenshot of your completed work.

**Comment by gsbakshi** [comment]
Hi @SonicDMG, I had created this on my local machine only. If you're talking about seeing the CRA readme, I had just changed my repo's readme yesterday

https://github.com/gsbakshi/todos-w-astra/tree/3ad7b6fc6516dd3405a744ea89e170ea20cf7ac4

This is the commit before I had updated my Readme.

And astra-todos.netlify.app/ is the link deployed app on Netlify

**Comment by SonicDMG** [comment]
Ok, this works for me. I see what you did with your github repo. Nice.

**Comment by HadesArchitect** [comment]
Hey **Gurmehar Singh Bakshi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/TRK-UBxjSSGrYplBf4_dvw
