### ISSUE TITLE
[HW] Abhay Khosla Building a Todo App Badge

### ISSUE THREAD

**Issue by Abhay2412** [datastaxdevs/appdev-week1-todolist#12]
**Name:** Abhay Khosla
**Email:** abhaykhosla0@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/abhaykhosla/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**_1. Login or Register to AstraDB and create database_**

The screenshot of the database being active in Astra DB: 
![Database List](https://user-images.githubusercontent.com/57297897/124782543-8d172e00-df01-11eb-8a8e-67a68383188c.png)

**_Screenshot of the React Todo Final App:(Step 2 Missing One)_**

![React Final Todo App](https://user-images.githubusercontent.com/57297897/125168650-be8f3400-e163-11eb-80e3-3cfa80ff03f9.png)

**_2. Create a security token_**
Cannot add the screenshot for this step due to security concerns. 

**_3. Create a table with REST API using Swagger_**
Screenshot of the Swagger UI with the V2 Create a Table Schema:
![Swagger UI V2 Schema](https://user-images.githubusercontent.com/57297897/124795847-c05fba00-df0d-11eb-8d18-25b50d216da3.png)

Keyspace and Body Updated Screenshot:
![KeySpaceName And Body](https://user-images.githubusercontent.com/57297897/124796341-4b40b480-df0e-11eb-8f73-d58a25484f34.png)

Execute Screenshot with the correct response 201:
![Execute Screen](https://user-images.githubusercontent.com/57297897/124796596-935fd700-df0e-11eb-881d-173ea5d71c4e.png)

**_4. Insert data in the Table with the REST API using Swagger_**
Creating the Add Row Step Screenshot:
![Creating Table Process](https://user-images.githubusercontent.com/57297897/124797070-197c1d80-df0f-11eb-98e6-561b249cc0cd.png)

Successful Post Request of the adding row Screenshot:
![Sucessful Execution](https://user-images.githubusercontent.com/57297897/124797210-42041780-df0f-11eb-9e5d-987c555f280e.png)

**_5. Retrieving values_**
Completion of the GET Request of the rows Screenshot:
![Get Request Completion ](https://user-images.githubusercontent.com/57297897/124797783-e5edc300-df0f-11eb-9e2f-8c3156e325b9.png)

**_6. Launch GitPod IDE_**
Screenshot of the GitPod IDE:
![GitPod interface](https://user-images.githubusercontent.com/57297897/124798936-3154a100-df11-11eb-9897-ebdadb60ded7.png)

**_7. Launch the TODO app_**
Screenshot of the Todo List with additional items:
![Todos Final Screenshot ](https://user-images.githubusercontent.com/57297897/124801110-b04ad900-df13-11eb-9613-251a6cd6aa41.png)

**Comment by SonicDMG** [comment]
Hi there Abhay, thank you for your submission. The todo app looks good, but I am missing the from scratch react app from step 2 of the homework.
2. Create a React app from scratch using NPX. Follow these instructions. Take a screenshot of your final working app.

Please complete that step and provide a screenshot of your completed work. Also, thank you for not posting your Astra tokens. :)

**Comment by Abhay2412** [comment]
Thanks, David I have done the React Todo List and added my screenshot.

**Comment by SonicDMG** [comment]
Ok, looks great, nice going.

**Comment by HadesArchitect** [comment]
Hey **Abhay Khosla**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/g0_eR6CsRJS8oKUPH168Zw
