### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by darbian** [datastaxdevs/appdev-week1-todolist#121]
**Name:** <Oleg Darbin>
**Email:** <oleg-darbin@yandex.ru>
**Linkedin Profile:** <> I can't create a LinkedIn account, because the service is blocked in Russia(even using a VPN, I can't register, I need a confirmation of the number, and I don't have a SIM card except for Russian LOL:,)). So is there any way to solve this moment?

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![ReactApp](https://user-images.githubusercontent.com/87287528/125220913-0df27300-e2d0-11eb-9611-2a1cf2a0c5b5.png)
![TODOS](https://user-images.githubusercontent.com/87287528/125225993-e358e800-e2d8-11eb-8f89-db56c529135e.png)

**Comment by SonicDMG** [comment]
The LinkedIn is optional. It's just a way to get your name for your badge. Well done BTW. If you would, drop the name you would like us to use and I'll get you a badge.

**Comment by SonicDMG** [comment]
I see you have issue https://github.com/datastaxdevs/appdev-week1-todolist/issues/123 with your name. I'll close this one out as a duplicate and use the other.
