### ISSUE TITLE
[HW] <Char Ryder>

### ISSUE THREAD

**Issue by bl-kt** [datastaxdevs/appdev-week1-todolist#127]
**Name:** Char Ryder
**Email:** char.ryder@blkt.co.uk
**Linkedin Profile:** https://www.linkedin.com/in/blkt/

Attach the homework screenshots below:
-----------------------------------------
![js app wk1 v1](https://user-images.githubusercontent.com/56833452/125271035-35623380-e302-11eb-9f89-f29824434f09.png)
![js app wk1 v2](https://user-images.githubusercontent.com/56833452/125271036-35faca00-e302-11eb-8e9b-c696964c8705.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Well done Char, thank you.

**Comment by HadesArchitect** [comment]
Hey **Char Ryder**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/HL5K20UNS4-PkR4bYEcDSw
