### ISSUE TITLE
[HW] Arinjay Gangwar

### ISSUE THREAD

**Issue by arinjayg** [datastaxdevs/appdev-week1-todolist#13]
**Name:** Arinjay Gangwar
**Email:** arinjay.gangwar100@gmail.com
**Linkedin Profile:** www.linkedin.com/in/arinjay-gangwar-1a3b93166

Attach the homework screenshots below:
-----------------------------------------
Step 3:
![Screenshot 2021-07-07 215004_LI](https://user-images.githubusercontent.com/76163860/124801519-8ece0980-df74-11eb-938d-a6cbe1cb2d2b.jpg)

Step 4:
![Screenshot 2021-07-07 215040_LI](https://user-images.githubusercontent.com/76163860/124801870-f71ceb00-df74-11eb-81e9-b06ee13a0afe.jpg)

Step 5:
![Screenshot 2021-07-07 215451_LI](https://user-images.githubusercontent.com/76163860/124802223-58dd5500-df75-11eb-8026-3ced2b38ca4d.jpg)

Gitpod:
![Screenshot 2021-07-07 221833_LI](https://user-images.githubusercontent.com/76163860/124802479-a35ed180-df75-11eb-8c54-bd3a06dd1cd7.jpg)

App Running:
![Screenshot 2021-07-07 222012](https://user-images.githubusercontent.com/76163860/124802638-d0ab7f80-df75-11eb-9a78-9df5442ea7c2.jpg)

Response From Server:
![Screenshot 2021-07-07 225302](https://user-images.githubusercontent.com/76163860/124802988-2ed86280-df76-11eb-8edd-9c04f6fb2521.jpg)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi there Arinjay, thank you for your submission. The todo app looks good, but I am missing the from scratch react app from step 2 of the homework.
2. Create a React app from scratch using NPX. Follow [these instructions](https://github.com/datastaxdevs/react-basics). Take a screenshot of your final working app.

Please complete that step and provide a screenshot of your completed work.

I'm glad you like the session, thank you. Have fun having lunch with mom. :)

**Comment by arinjayg** [comment]
React app from Scratch
![Screenshot 2021-07-10 085639](https://user-images.githubusercontent.com/76163860/125150384-1b3b2080-e15d-11eb-84da-d06b1c94c9f2.jpg)
![Screenshot 2021-07-10 085700](https://user-images.githubusercontent.com/76163860/125150391-21c99800-e15d-11eb-8a4d-2cdf76f27008.jpg)

**Comment by arinjayg** [comment]
Hi David,
I have now completed my Homework, I misunderstood the second step so sorry
for the Mistake.
Kindly Recheck it :) and Have a nice day :)

Link:
https://github.com/datastaxdevs/appdev-week1-todolist/issues/13#issuecomment-877553304

**Comment by clun** [comment]
Great job !

**Comment by HadesArchitect** [comment]
Hey **Arinjay Gangwar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/4JvNxDlpQaacBjFC0n_Brw
