### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by juliann** [datastaxdevs/appdev-week1-todolist#15]
**Name:** <Julian Nadarzy>
**Email:** <julian.nadarzy@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/julian-nadarzy-74b7b810/

Attach the homework screenshots below:
-----------------------------------------

![gitpod ](https://user-images.githubusercontent.com/1125748/124806600-2b84ad00-df5d-11eb-8873-de9601b6077c.jpg)
![local react app](https://user-images.githubusercontent.com/1125748/124806602-2c1d4380-df5d-11eb-9419-890a39bafc01.jpg)
![task 1](https://user-images.githubusercontent.com/1125748/124806603-2c1d4380-df5d-11eb-8e6e-fdd2b333fed5.jpg)
![task 5](https://user-images.githubusercontent.com/1125748/124806604-2cb5da00-df5d-11eb-99a8-d85952df510d.jpg)
>

**Comment by SonicDMG** [comment]
Great job Julian, everything looks good and thank you for covering up your tokens. Here's your badge -> https://api.badgr.io/public/assertions/4Ln9MWXBQJetlncamkD8vQ?identity__email=julian.nadarzy%40gmail.com

I see you completed taking over the Moon, seems like a nice vacation spot. ;)
