### ISSUE TITLE
[HW] Michelle Greyson wk1

### ISSUE THREAD

**Issue by michellengreyson** [datastaxdevs/appdev-week1-todolist#186]
**Name:** Michelle Greyson
**Email:** michellengreyson@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/michellengreyson/

Attach the homework screenshots below:
-----------------------------------------

![Screenshot (49)](https://user-images.githubusercontent.com/56977312/126510862-287ea563-6750-4bb2-a9bc-c03ea79eb526.png)
![Screenshot (50)](https://user-images.githubusercontent.com/56977312/126510889-beed1dcd-3feb-4d8c-a31e-536f41b98b71.png)

**Comment by HadesArchitect** [comment]
Hey **Michelle Greyson**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qKfAxiOyTmq_YYFLjjDLPg

**Comment by michellengreyson** [comment]
Thanks so much! Learned a ton :)
