### ISSUE TITLE
[HW] Week 1 Todo App

### ISSUE THREAD

**Issue by samarthbansal258** [datastaxdevs/appdev-week1-todolist#199]
**Name:** Samarth Bansal
**Email:** samarth.bansal@pathways.in
**Linkedin Profile:** https://www.linkedin.com/in/samarth-bansal-06b043218/

Attach the homework screenshots below:

-----------------------------------------
Todo App -
<img width="1440" alt="Screenshot 2021-07-24 at 1 54 27 PM" src="https://user-images.githubusercontent.com/86355086/126862929-ba1ef002-eae1-443f-99f3-dea7626f59a0.png">

React App - (With Check Boxes)
<img width="1440" alt="Screenshot 2021-07-24 at 2 08 22 PM" src="https://user-images.githubusercontent.com/86355086/126862975-fcc40e85-e264-412f-8e53-9e182ea72f19.png">
 
(With changing background when mouse hovers over the words on the list)
<img width="1440" alt="Screenshot 2021-07-24 at 2 09 57 PM" src="https://user-images.githubusercontent.com/86355086/126863077-7bab2df6-6e94-4501-874a-d33ef20db0d9.png">
<img width="1440" alt="Screenshot 2021-07-24 at 2 09 52 PM" src="https://user-images.githubusercontent.com/86355086/126863081-73c51553-cc69-4f5d-8ee9-b2cb820d56b2.png">

**Comment by HadesArchitect** [comment]
Hey **Samarth Bansal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Onlsz188QeO0LVtFn4CcKw
