### ISSUE TITLE
[HW-08-09-2021] <RAHUL BHOJAK> 

### ISSUE THREAD

**Issue by Rahulbhojak** [datastaxdevs/appdev-week1-todolist#240]
**Name:** RAHUL BHOJAK
**Email:** rahulbhojak@gmail.com
**Linkedin Profile:** linkedin.com/in/rahulbhojak

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![hello warld](https://user-images.githubusercontent.com/87692451/132572206-6bd11f34-9e71-4042-94ad-b84c109cb0d7.png)

**Comment by hemidactylus** [comment]
I'm closing this since it's a duplicate of #241

**Comment by Rahulbhojak** [comment]
Got it, thanks!
