### ISSUE TITLE
[HW] Nora Sumane

### ISSUE THREAD

**Issue by nora-sch** [datastaxdevs/appdev-week1-todolist#248]
**Name:** Nora Sumane
**Email:** nora.sumane@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nora-sumane/

Attach the homework screenshots below:
-----------------------------------------
<img src="https://user-images.githubusercontent.com/62623658/132699791-3976eff1-a0d2-480b-82d4-373407b9e4e6.JPG" alt="drawing" width="700"/>
<img src="https://user-images.githubusercontent.com/62623658/132699844-d8df728d-1ba0-4a65-836a-0680aa74ec65.JPG" alt="drawing" width="700"/>
<img src="https://user-images.githubusercontent.com/62623658/132699868-dbe8593e-1403-40ce-aaec-004c91fd1fd0.JPG" alt="drawing" width="700"/>
<img src="https://user-images.githubusercontent.com/62623658/132699913-7f3c9766-14b6-4c7c-ac7b-bbad13f5f7d0.JPG" alt="drawing" width="700"/>

-----------------------------------------
<img src="https://user-images.githubusercontent.com/62623658/132699975-bc1296a8-2bba-489b-b933-fa34ccc24b68.JPG" alt="drawing" width="700"/>
<img src="https://user-images.githubusercontent.com/62623658/132699985-86df2ce4-6c7b-4a45-8c96-d68c007b723e.JPG" alt="drawing" width="700"/>

**Comment by HadesArchitect** [comment]
Hey **Nora Sumane**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/zuw3eLhFSz-d23ZD8i66-g

**Comment by nora-sch** [comment]
> Hey **Nora Sumane**, gngrats!
