### ISSUE TITLE
[HW] Bhaskar Pal

### ISSUE THREAD

**Issue by pal-bhaskar** [datastaxdevs/appdev-week1-todolist#253]
**Name:** BHASKAR PAL
**Email:** bhaskarpaal@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/bhaskar-pal-3364758a/

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-09-10 at 10 29 52 AM](https://user-images.githubusercontent.com/69039695/132802657-ed7b0d25-7639-47a7-b643-4f33755bb37e.png)
-- images removed by team --
![Screenshot 2021-09-10 at 10 08 53 AM](https://user-images.githubusercontent.com/69039695/132802699-4835721e-f13c-4bfa-9673-a83397e4c8db.png)
![Screenshot 2021-09-10 at 10 07 59 AM](https://user-images.githubusercontent.com/69039695/132802704-60014211-b830-40ea-ad0a-fd79c272cf6b.png)
![Screenshot 2021-09-10 at 10 07 36 AM](https://user-images.githubusercontent.com/69039695/132802708-862f9253-4342-4547-a974-fbae64588b09.png)
![Screenshot 2021-09-10 at 10 01 57 AM](https://user-images.githubusercontent.com/69039695/132802713-5a7343a2-60da-4c9f-a05a-1808824e060b.png)
![Screenshot 2021-09-10 at 10 01 50 AM](https://user-images.githubusercontent.com/69039695/132802714-a7acce38-d247-4bf9-ad58-6ab1b9866a90.png)
![Screenshot 2021-09-10 at 9 57 20 AM](https://user-images.githubusercontent.com/69039695/132802716-7c7fe1b7-6e7a-482f-9c94-20091b60710e.png)

**Comment by HadesArchitect** [comment]
Hey **BHASKAR PAL**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ujZChWvIQ624XgRz0qbaEw

**Comment by SonicDMG** [comment]
Also, I had to remove a set of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.

**Comment by pal-bhaskar** [comment]
Thanks @HadesArchitect , @SonicDMG !!
