### ISSUE TITLE
[HW] <SHAIKH MOHD NOMAN>

### ISSUE THREAD

**Issue by noman318** [datastaxdevs/appdev-week1-todolist#37]
**Name:** Shaikh Mohd Noman
**Email:** shaikhmohdnoman612@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/shaikh-mohd-noman-769917215
![datastaxHW](https://user-images.githubusercontent.com/74728455/124938707-25a6ce80-e026-11eb-9a69-7bbbb30de4c5.png)

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi there Shaikh, thank you for your submission. The todo app looks good, but I am missing the from scratch react app from step 2 of the homework.
2. Create a React app from scratch using NPX. Follow [these instructions](https://github.com/datastaxdevs/react-basics). Take a screenshot of your final working app.

Please complete that step and provide a screenshot of your completed work.

**Comment by noman318** [comment]
![datastaxHW2](https://user-images.githubusercontent.com/74728455/125647737-876d93a3-591f-4470-9947-2acb96465c04.png)

**Comment by HadesArchitect** [comment]
Hey **Shaikh Mohd Noman**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qcIki8upQo-dxfTTsFN3Jg
