### ISSUE TITLE
Rohan Goyal

### ISSUE THREAD

**Issue by 37rohan** [datastaxdevs/appdev-week1-todolist#38]
**Name:** Rohan Goyal
**Email:** rohangoyal264@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rohan-goyal-3a1744200/

Attach the homework screenshots below:
-----------------------------------------
# React app Using NPX:
![Screenshot_3](https://user-images.githubusercontent.com/76154317/124940214-66ebae00-e027-11eb-92f0-8c0e29fcf81f.png)
![Screenshot_7](https://user-images.githubusercontent.com/76154317/124940308-7ec33200-e027-11eb-93a3-dc983bbebc00.png)

# Todo Starter App:
### Step1: Creating Table:
-- images removed by team --

### Step4: Launching Todo Apps:
![Screenshot_8](https://user-images.githubusercontent.com/76154317/124941784-b1215f00-e028-11eb-979f-a81dd90392fc.png)
![Screenshot_4](https://user-images.githubusercontent.com/76154317/124941840-bda5b780-e028-11eb-821a-48d21be587cb.png)

![Screenshot_11](https://user-images.githubusercontent.com/76154317/124942655-723fd900-e029-11eb-9b4a-032580517fa8.png)
![Screenshot_5](https://user-images.githubusercontent.com/76154317/124942175-078e9d80-e029-11eb-88ca-80309ef4f606.png)
![Screenshot_6](https://user-images.githubusercontent.com/76154317/124942161-02c9e980-e029-11eb-8e5e-878ca31c89ef.png)

**Comment by SonicDMG** [comment]
Very nice job Rohan, I see you got through everything, great. Here's your badge -> https://api.badgr.io/public/assertions/FzaYs28ZSjyqTHhIWhmgew?identity__email=rohangoyal264%40gmail.com

**Comment by SonicDMG** [comment]
Also, I removed a set of images that included your Astra token. Please ensure to delete your token from the Astra UI so we don't have any security holes, thank you.
