### ISSUE TITLE
[HW] Lee Yong Wei

### ISSUE THREAD

**Issue by fackerlee** [datastaxdevs/appdev-week1-todolist#45]
**Name:** Lee Yong Wei
**Email:** fackerlee@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/yongw3i/

Attach the homework screenshots below:
-----------------------------------------

![HW-1](https://user-images.githubusercontent.com/76558523/124964225-58b38700-e053-11eb-8479-c73e10e42e24.png)
<br>
![HW-2](https://user-images.githubusercontent.com/76558523/124964361-83054480-e053-11eb-9c2d-0f3d6d50be49.png)

**Comment by SonicDMG** [comment]
Great job Lee, thank you. Here's your badge -> https://api.badgr.io/public/assertions/q-3tjmPvTJqkP-onQ-wXXw?identity__email=fackerlee%40gmail.com
